# Generated by Django 4.2.4 on 2023-08-21 01:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("batch_managing", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="batch",
            name="id",
        ),
        migrations.AlterField(
            model_name="batch",
            name="reference",
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
