# Generated by Django 4.2.4 on 2023-08-21 12:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("batch_managing", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrderLine",
            fields=[
                (
                    "reference",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("sku", models.CharField(max_length=255)),
                ("qty", models.IntegerField()),
            ],
        ),
    ]
