# Generated by Django 4.2.4 on 2023-08-21 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("batch_managing", "0003_orderline_batch"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="orderline",
            name="batch",
        ),
        migrations.AddField(
            model_name="batch",
            name="line",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="batch_managing.orderline",
            ),
        ),
    ]
