# Generated by Django 4.2.4 on 2023-08-21 13:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("batch_managing", "0004_remove_orderline_batch_batch_line"),
    ]

    operations = [
        migrations.RenameField(
            model_name="batch",
            old_name="line",
            new_name="order_line",
        ),
    ]
